name: UNAST
channels:
  - pytorch
  - defaults
dependencies:
  - cpuonly=1.0=0
  - matplotlib=3.3.4
  - numpy=1.19.2
  - pandas=1.1.3
  - python=3.6.13
  - pytorch=1.8.1
  - scipy=1.5.2
  - tensorboard=1.14.0
  - torchaudio=0.8.1
  - torchvision=0.9.1
  - tqdm=4.59.0
  - unidecode=1.2.0
  - inflect=5.3.0
